events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream django_backend {
        server web:8000;
    }

    server {
        listen 80;
        server_name cafitdaw.freemyip.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        http2 on;
        server_name cafitdaw.freemyip.com;

        ssl_certificate /etc/letsencrypt/live/cafitdaw.freemyip.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/cafitdaw.freemyip.com/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:10m;
        ssl_session_tickets off;

        location /static/ {
            alias /app/static/;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }

        location / {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
