events {}
http {
    upstream django_backend {
        server web:8000;
    }
    server {
        listen 80;
        server_name cafit.freemyip.com;
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        location / {
            return 301 https://$host$request_uri;
        }
    }
    server {
        listen 443 ssl;
        server_name cafit.freemyip.com;
        ssl_certificate /etc/letsencrypt/live/cafit.freemyip.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/cafit.freemyip.com/privkey.pem;

        location /static/ {
            alias /app/staticfiles/;
        }
        location / {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
        }
    }
}
