# Generated by Django 5.2.11 on 2026-04-14 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=200)),
                ('unidad', models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unidad', 'Unidad'), ('cucharada', 'Cucharada'), ('taza', 'Taza')], default='g', max_length=20)),
                ('cantidad_referencia', models.FloatField(default=100, help_text='Cantidad base para los macros')),
                ('kcal', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('azucares', models.FloatField(default=0)),
                ('grasas', models.FloatField()),
                ('saturadas', models.FloatField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snacks', 'Snacks')], max_length=20)),
                ('fecha_comida', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_comida', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ComidaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_snapshot', models.CharField(help_text='Nombre del alimento al momento de registrar', max_length=200)),
                ('marca_snapshot', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.FloatField()),
                ('unidad', models.CharField(max_length=20)),
                ('kcal', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('azucares', models.FloatField()),
                ('grasas', models.FloatField()),
                ('saturadas', models.FloatField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('alimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.alimento')),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comida_alimentos', to='config.comida')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('esta_oculto', models.BooleanField(default=False)),
                ('estado_moderacion', models.CharField(choices=[('visible', 'Visible'), ('oculto', 'Oculto'), ('pendiente_revision', 'Pendiente de revisión')], default='visible', max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='config.salachat')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], default='abierta', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('nota_admin', models.TextField(blank=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_atendidas', to=settings.AUTH_USER_MODEL)),
                ('reportero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='config.mensajechat')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, help_text='En cm', null=True)),
                ('peso', models.FloatField(blank=True, help_text='En kg', null=True)),
                ('sexo', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('otro', 'Prefiero no decirlo')], default='hombre', max_length=20)),
                ('objetivo', models.CharField(choices=[('perder_grasa', 'Perder grasa'), ('mantener_peso', 'Mantener peso'), ('ganar_musculo', 'Ganar masa muscular')], default='mantener_peso', max_length=20)),
                ('meta_calorias', models.IntegerField(blank=True, null=True)),
                ('meta_proteinas', models.IntegerField(blank=True, null=True)),
                ('meta_grasas', models.IntegerField(blank=True, null=True)),
                ('meta_carbohidratos', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
