# Generated by Django 5.2.11 on 2026-04-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_remove_unused_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimento',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='comida',
            options={'ordering': ['-fecha_comida']},
        ),
        migrations.AlterModelOptions(
            name='incidencia',
            options={},
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='comidaalimento',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='creada_en',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='mensajechat',
            name='esta_oculto',
        ),
        migrations.RemoveField(
            model_name='mensajechat',
            name='estado_moderacion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='creado_en',
        ),
        migrations.AlterField(
            model_name='alimento',
            name='unidad',
            field=models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unidad', 'Unidad')], default='g', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='objetivo',
            field=models.CharField(choices=[('bajar_peso', 'Bajar de peso'), ('mantener_peso', 'Mantener peso'), ('ganar_peso', 'Ganar peso')], default='mantener_peso', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='hombre', max_length=20),
        ),
    ]
