from django.contrib import admin
from django.urls import path
from config.views import (
    inicio,
    acceso,
    registro,
    cerrar_sesion,
    chat,
    chat_sala,
    chat_mensajes_nuevos,
    perfil,
    estadisticas,
    completar_perfil,
    panel_admin,
    dashboard,
    agregar_comida_inicio,
    agregar_comida_detalle,
    editar_comida,
    borrar_comida,
    admin_incidencias,
    admin_chat,
    admin_usuarios,
    reportar_problema,
    alimentos,
    alimentos_detalle,
    eliminar_usuario,
    editar_alimento,
)
from config.views import eliminar_alimento


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", inicio, name="inicio"),
    path("acceso/", acceso, name="acceso"),
    path("registro/", registro, name="registro"),
    path("salir/", cerrar_sesion, name="cerrar_sesion"),
    path("chat/", chat, name="chat"),
    path("chat/sala/<slug:sala_slug>/", chat_sala, name="chat_sala"),
    path("chat/sala/<slug:sala_slug>/mensajes-nuevos/", chat_mensajes_nuevos, name="chat_mensajes_nuevos"),
    path("perfil/completar/", completar_perfil, name="completar_perfil"),
    path("perfil/", perfil, name="perfil"),
    path("perfil/estadisticas/", estadisticas, name="estadisticas"),
    path("perfil/reportar-problema/", reportar_problema, name="reportar_problema"),
    path("panel-admin/", panel_admin, name="panel_admin"),
    path("dashboard/", dashboard, name="dashboard"),
    path("comidas/nueva/", agregar_comida_inicio, name="agregar_comida_inicio"),
    path("comidas/detalle/", agregar_comida_detalle, name="agregar_comida_detalle"),
    path("comidas/<int:indice_comida>/editar/", editar_comida, name="editar_comida"),
    path("comidas/<int:indice_comida>/borrar/", borrar_comida, name="borrar_comida"),
    path("alimentos/", alimentos, name="alimentos"),
    path("alimentos/<int:id>/detalle/", alimentos_detalle, name="alimentos_detalle"),
    path("alimentos/<int:id>/editar/", editar_alimento, name="editar_alimento"),
    path("alimentos/<int:id>/eliminar/", eliminar_alimento, name="eliminar_alimento"),
    path("panel-admin/incidencias/", admin_incidencias, name="admin_incidencias"),
    path("panel-admin/chat/", admin_chat, name="admin_chat"),
    path("panel-admin/usuarios/", admin_usuarios, name="admin_usuarios"),
    path("panel-admin/usuarios/<int:id>/eliminar/", eliminar_usuario, name="eliminar_usuario"),

]